name: minTYN Build and Test

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Build and Test Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Build with Maven
        run: mvn clean package

      - name: Verify with Maven
        run: mvn clean verify

      - name: Run Unit Tests
        run: mvn test -Dtest=com.cardpluse.service.*Test 
