name: minTYN Build and Test

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Build and Test Project
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: cardInsight
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify with Maven
        run: mvn clean verify -DskipTests

      - name: Run Unit Tests
        env:
          DB_URL: jdbc:mysql://localhost:3306/cardInsight
          DB_USERNAME: root
        run: |
          mvn test -Dtest=com.cardpluse.service.CardInfoServiceImplTest,com.cardpluse.service.UserServiceImplTest \
            -Dspring.datasource.url=$DB_URL \
            -Dspring.datasource.username=$DB_USERNAME \
            -Dspring.datasource.password=


